### PR TITLE
Use build task instead of check

### PR DESCRIPTION
**Pull request by CherryPerry**
Fixes https://github.com/badoo/Reaktive/issues/224

Build = compile everything + check

### CODE REVIEW

**Comment by arkivanov** [comment]
But what about tests. Looks like they all are skipped now. And there is no test task involved for linuxArm32Hfp

**Comment by CherryPerry** [comment]
@arkivanov `linuxX64Test` tasks were executed, but no output is available. Looks like test's results were cached, I didn't change code. In the last `master` [build](https://travis-ci.org/badoo/Reaktive/jobs/594836252) there is no test output too.

We can't execute tests for `arm` on `x86_64`. Only `LinuxX64` is tested.
The same for iOS builds: we test only `iosSim`, but not `iosArm32` and  `iosArm64`.

**Comment by arkivanov** [comment]
Why? I can run linuxArm32 tests locally on my Ubuntu host. "Linux MIPS targets (linuxMips32 and linuxMipsel32) require a Linux host. Other Linux targets can be built on any supported host;"

**Comment by CherryPerry** [comment]
Can you show me your Gradle tasks of `verification` group of `:reaktive` module?

**Comment by arkivanov** [comment]
Hmm, looks like I'm wrong. There is no linux arm 32 test task there.

**Pull request merged**
