### PR TITLE
1.4-M3 support

### PR DESCRIPTION
**Pull request by CherryPerry**
@arkivanov 

It is possible to work with now.
We can force merge this ticket and you can fix all appeared issues (at least 1 small fix and one IR backend error in coroutines lib) in different one.

### CODE REVIEW

**Comment by arkivanov** [comment]
Looks like 1.4-M3 is out :-)

**Comment by CherryPerry** [comment]
@arkivanov fixed.
Feel free to merge.
The project won't build because of compilation issues.

**Comment by arkivanov** [comment]
> @arkivanov fixed.
> Feel free to merge.
> The project won't build because of compilation issues.

Why it does not build? How we will work on the branch if it does not compile?

**Comment by CherryPerry** [comment]
I encountered IR backend exception in coroutines module. I don't want to fix it.
You can sync the project (that was not available before) now and fix all compilation errors.
You can merge this ticket into kotlin-1.4 branch and create separate PR with compilation fixes. Or you can fix it in this branch.

**Pull request merged**
