### PR TITLE
Implemented replay with bufferSize

### LINKED ISSUE #313: Replay count
It would be great if `replay()` accepted a count of items to replay (from the end) on subscription.

### PR DESCRIPTION
**Pull request by arkivanov**
Fixes #313

### CODE REVIEW

**Comment by saket** [comment]
🎉 

Do you publish snapshots?

**Comment by CherryPerry** [comment]
No, but I will investigate possibilities.

**Comment by arkivanov** [comment]
We will release next version after #315 . I'm working on it.

**Comment by saket** [comment]
Got it, thank you!

**Pull request merged**
