### PR TITLE
Yarn namespace fix

### PR DESCRIPTION
**Pull request by CherryPerry**
https://youtrack.jetbrains.com/issue/KT-48407/KJS-Yarn-fails-when-both-local-and-remote-library-versions-in-project

### CODE REVIEW

**Comment by arkivanov** [comment]
> upload build/js/package.json

This looks unnecessary? Are there any issues currently?

**Comment by CherryPerry** [comment]
Debugging on CI, still have the issue with publishing.

**Comment by CherryPerry** [comment]
```json
{
  "name": "Reaktive-root",
  "version": "unspecified",
  "private": true,
  "workspaces": [
    // this one is our local
    "packages/Reaktive-root-reaktive-js-legacy",
    // this one we receive from repository, same name
    "packages_imported/Reaktive-root-reaktive-js-legacy/1.2.2",
  ],
  "resolutions": {},
  "devDependencies": {},
  "dependencies": {},
  "peerDependencies": {},
  "optionalDependencies": {},
  "bundledDependencies": []
}
```

I will disable JS in `check-publication`, OK? @arkivanov

**Comment by arkivanov** [comment]
See an example: https://github.com/arkivanov/Decompose/blob/d112f923a417b2923bf5478954728acfaef7d8cb/settings.gradle.kts#L46

**Comment by CherryPerry** [comment]
I think it is even more simple to never include `publication-check` into the main `settings.gradle` and keep it separated.

**Comment by CherryPerry** [comment]
@arkivanov review pls.

**Comment by arkivanov** [comment]
LGTM

**Review by arkivanov — APPROVED** [review]

**Pull request merged**
