### PR TITLE
Switch to official compatibility validator plugin

### PR DESCRIPTION
**Pull request by emartynov**
## Task
Switch from the for to official JetBrain plugin - Fix for #608

## Changes
* Remove for of the plugin
* Update official plugin version

## Notes
* Not sure where is magic - I didn't find why removal of fork automatically switch to official plugin. Also according to [official documentation](https://github.com/Kotlin/binary-compatibility-validator) I have to change plugin id. However, this broke the gradle sync. So I kept plugin id as it is and command line just worked fine.

### CODE REVIEW

**Comment by CherryPerry** [comment]
Can you remove existing `api` folders and create new dump using [apiDump](https://github.com/Kotlin/binary-compatibility-validator#tasks) please? Looks like new version has new `api` folder structure, so `apiCheck` on CI check will fail.

> Not sure where is magic

[Included build](https://docs.gradle.org/current/userguide/composite_builds.html) replaces remote artefacts when has the same publication id and version.

**Comment by emartynov** [comment]
I hope, I did everything correct.

**Review by CherryPerry — APPROVED** [review]

**Comment by emartynov** [comment]
Don't you people squash PRs?

**Comment by CherryPerry** [comment]
By default – no, your commit history looks fine enough.

**Pull request merged**
