### PR TITLE
Mark classes that use DisposableScope with UseExperimental

### PR DESCRIPTION
**Pull request by mayokunthefirst**
Fixes issue #379

### CODE REVIEW

**Comment by CherryPerry** [comment]
```
w: /Users/runner/runners/2.163.1/work/Reaktive/Reaktive/sample-mpp-module/src/darwinCommonMain/kotlin/com/badoo/reaktive/samplemppmodule/KittenStoreBuilderImpl.kt: (9, 41): This declaration is experimental and its usage should be marked with '@com.badoo.reaktive.annotations.ExperimentalReaktiveApi' or '@UseExperimental(com.badoo.reaktive.annotations.ExperimentalReaktiveApi::class)'
```

Now `KittenStoreBuilderImpl` uses experimental features.

I think it is better to use `@UseExperimental(ExperimentalReaktiveApi::class)` in `sample-mpp-module` for all cases, because module itself just uses new unstable API and do not exposes it.

So my proposal – mark all files that uses `DisposableScope` with `@UseExperimental(ExperimentalReaktiveApi::class)` and it should be enough. But better to check it locally and on CI after change.

**Comment by mayokunthefirst** [comment]
> ```
> w: /Users/runner/runners/2.163.1/work/Reaktive/Reaktive/sample-mpp-module/src/darwinCommonMain/kotlin/com/badoo/reaktive/samplemppmodule/KittenStoreBuilderImpl.kt: (9, 41): This declaration is experimental and its usage should be marked with '@com.badoo.reaktive.annotations.ExperimentalReaktiveApi' or '@UseExperimental(com.badoo.reaktive.annotations.ExperimentalReaktiveApi::class)'
> ```
> 
> Now `KittenStoreBuilderImpl` uses experimental features.
> 
> I think it is better to use `@UseExperimental(ExperimentalReaktiveApi::class)` in `sample-mpp-module` for all cases, because module itself just uses new unstable API and do not exposes it.
> 
> So my proposal – mark all files that uses `DisposableScope` with `@UseExperimental(ExperimentalReaktiveApi::class)` and it should be enough. But better to check it locally and on CI after change.

@CherryPerry after implementing this, I keep getting these warnings:
````
w: /home/runner/work/Reaktive/Reaktive/reaktive/src/commonMain/kotlin/com/badoo/reaktive/annotations/Annotations.kt: (5, 2): This class can only be used with the compiler argument '-Xuse-experimental=kotlin.Experimental'
w: /home/runner/work/Reaktive/Reaktive/reaktive/src/commonMain/kotlin/com/badoo/reaktive/annotations/Annotations.kt: (5, 15): This class can only be used with the compiler argument '-Xuse-experimental=kotlin.Experimental'
w: /home/runner/work/Reaktive/Reaktive/reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/scope/DisposableScopeImpl.kt: (16, 2): This class can only be used with the compiler argument '-Xuse-experimental=kotlin.Experimental'
````

**Comment by CherryPerry** [comment]
@mayokunthefirst It is fine.

**Comment by mayokunthefirst** [comment]
> @mayokunthefirst It is fine.

@CherryPerry Oh, awesome then, but out of curiosity, if it's not too much too ask, would love to know if getting rid of such warning would involve something like adding such line `-Xuse-experimental=kotlin.Experimental` to the `gradle.properties` file, something similar to enabling incremental annotation processing `kapt.incremental.apt` or enabling jetifier i.e. `android.enableJetifier`?

**Comment by CherryPerry** [comment]
It is a little harder to do. You need to add special parameter to every source set in every module. I will think, how to implement it better than just applying it via `allProjects { ... }`.

[Link.](https://kotlinlang.org/docs/reference/experimental.html#module-wide-use)

**Comment by mayokunthefirst** [comment]
> It is a little harder to do. You need to add special parameter to every source set in every module. I will think, how to implement it better than just applying it via `allProjects { ... }`.
> 
> [Link.](https://kotlinlang.org/docs/reference/experimental.html#module-wide-use)

Alright then, thank you.

**Pull request merged**
